- .github/ISSUE_TEMPLATE/question.md
gofmt() is changed to send in source code needing gofmt'ing directly into the gofmt process via stdin instead of first being written to a temp file.
This causes a change in output, as shown below.
Old:
```sh
2019/03/29 23:42:55 Error from ParserGoPkg: error parsing "root.vugu": go fmt error exit status 2; full output: /home/erin/workspace/vuguexample/ParserGo451043648.go:32:26: expected ';', found nope
```
New:
```sh
2019/03/29 23:44:43 Error from ParserGoPkg: error parsing "root.vugu": go fmt error exit status 2; full output: <standard input>:32:26: expected ';', found nope
```
> ParserGo works with fewer temp files

- simplehttp/simple-handler.go
Safari (both macOS and iOS) have no support for `WebAssemly.instantiateStreaming` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming)).
This patch polyfills the missing function as suggested by the main [go wasm wiki](https://github.com/golang/go/wiki/WebAssembly) ([code snippet](https://github.com/golang/go/blob/b2fcfc1a50fbd46556f7075f7f1fbf600b5c9e5d/misc/wasm/wasm_exec.html#L17-L22))
> Added instantiateStreaming polyfill to support Safari

- .travis.yml
- README.md
You'll need to give TravisCI access to the repo to get the build badge working.
> adding pretty badges

- .gitattributes
This only brings a more handy way to generate the script, because
currently you need to go to the domrender directory and execute `go run
renderer-js-script-maker.go`, with this you can just run `go generate ./...`
at the root level.
The change also contains a git option to remove the generated file from
the git diff (because it's annoying and useless).
There's room for improvement, like integrating this step in the build
process, but this requires a Makefile or something similar (Mage?).
Moreover something may come from the std lib on that topic :)
https://github.com/golang/go/issues/35950
> ignore generated domrender file from diff

- gen/parser-util.go
- wasm-test-suite/test-007-issue-85/.gitignore
- wasm-test-suite/test-007-issue-85/comp.vugu
- wasm-test-suite/test-007-issue-85/go.mod
- wasm-test-suite/test-007-issue-85/root.vugu
- wasm-test-suite/wasm-suite_test.go
Fix #85
The fix is straightforward. Because the field name case is important since
the last refactor, we should always deal with attr.OrigKey and never attr.Key.
Note: we could remove `attrFromHtml` func and inline it inside `staticVGAttr`, since it's only used here.
> Fix static fields always considered as attrMap

- gen/parser-go.go
this implements #122 for all locations where dynamic attributes are
supported. In the initial commit, i missed some places where these kind
of attributes are handled.
> Handle dynamic attributes correctly in all places

- internal/htmlx/token.go
This would resolve the vugufmt lowering mentioned in #192 and #154 (apologies for not looking more before creating my own issue).
The two calls to TagName still use the same code path that they were before in my testing. The related tests also still passed.
> remove lower() call on tokens with colons

- .github/workflows/go.yml
I couldn't register my fork on Travis CI, so I decided to just use Github actions instead.
> Use Github Actions instead of Travis

- gen/parser-go.go
Hello,
This PR goes with https://github.com/vugu/vugu/issues/246 requirements.
When I was doing some tests, I was having a body like:
```html
<body>
<div>1st div</div>
<div>2nd div</div>
</body>
```
instead of:
```html
<body>
<div>
<div>1st div</div>
<div>2nd div</div>
</div>
</body>
```
The original error message wasn't clear.
> Improve foundMountEl error message from visitBody func

- .github/workflows/go.yml
Hello @bradleypeabody @owenwaller ,
I'm just changing the way of installing `golangci-lint` to avoid golang version issues.
It's related to https://github.com/vugu/vugu/pull/252#issuecomment-1826965915 for `go 1.17.x`
> Install golangci-lint with deb package instead of building it

- vugufmt/doc.go
Correct the vugufmt test failure by correcting the doc.go file to add an additional space to the comment. The test failure was in TestGoFmtNoError
This fix is also part of PR261. This commit breaks the fix out.
> Correct the vugufmt test failure

- Taskfile.yaml
- wasm-test-suite/docker/go.mod
Use a Taskfile (see: https://taskfile.dev/) to build the vugu packages, the vugugen and vugufmt command line tools, run all of the tests, and lint the source code.
This simplifies building vugu locally. All that is required now is
$ task all
at the top level of the repo. The Taskfile.yaml is fully documented.
Note: this is an initial version that only supports Linux as it relies on command line utilities that are installed by default on Linux. In addition it assumes that docker, tinygo and the golangci-lint tools are all installed locally. If they are not found then the task will abort. Supporting Windows will require changing the tasks to support the Windows PowerShell equivalents when the task in run on Windows.
> Use a Taskfile to build and test vugu

- legacy-wasm-test-suite/docker/Dockerfile
This is to fix the issue with the legacy test suite where it looks like it was erroring due to the remote debugging functionality changing.  To fix this up properly to work with the latest version would require further reworking the guts of the docker setup for this so I instead just pinned it to the last working version.  The plan is to get rid of this entirely in the long run so I think this is fine.
> pinned to older chrome version

- .github/workflows/go.yml
- magefiles/gitcmd.go
- magefiles/magefile.go
The approach to checking for outdated generated files in the repo was a little overzealous. It actually prevented building locally if the git repo was dirty i.e. had modified files.
This commit corrects that, by restoring the ability to build, test, and run the examples locally with a dirty repo.
The magefile now supports 6 new targets:
BuildWithGeneratedFilesCheck - which is like Build but adds the generated file check
TestWasmWithGeneratedFilesCheck - which is like TestWasm but adds the generated file check
TestSingleWasmTestWithGeneratedFilesCheck - which is like TestSingleWasmTest but adds the generated file check
ExamplesWithGeneratedFilesCheck - which is like Examples but adds the generated file check.
SingleExampleWithGeneratedFilesCheck - which is like SingleExample but adds the …
> Restore the ability to build, test and run examples locally with a dirty repo

- magefiles/magefile.go
Added a pair of new targets:
SingleWasmTest and SingleWasmTestWithGeneratedFileCheck
Both targets start the named wasm-test-suite module, and serve it via a local nginx instance.
For example:
mage SingleExample gtihub.com/vugu/vugu/wasm-test-suite/test-002-click
would be served at:
http://localhost:8888/test-0020-click
This is useful if the behaviour of a test or the structure of the HTML has to be examined in a browser. This can be useful in debugging the tests.
The SingleWasmTestWithGeneratedFilesCheck target is the same but adds the generated files check.
> Add a new target SingleWasmTest to build and serve a single wasm test

- .github/workflows/go-oldstable.yml
- .github/workflows/go-stable.yml
- .github/workflows/go.yml
Now that the go v1.22 `for` loop shadowing changes are the default, and go v1.23 has been released we can now support building `vugu` with the last two supported versions of Go - aka `stable` and `oldstable`.
The definition of `stable` and `oldstable` is per the [go-versions](https://github.com/actions/go-versions/blob/main/versions-manifest.json) repo. Basically Go v1.X and Go v1.(X-1) both at the latest patch level.
Currently the `stable` build fails because `tinygo` does not yet support go v1.23. This will resolve itself in time, once the latest `tinygo` docker container is updated so support go v1.23.
The `oldstable` build completes normally without error.
Github Action jobs are only cleanly separated into a different containers/vm's(?) if each job is a separate YAML file. We require …
> Build vugu with last two supported Go versions

- devutil/tinygo-compiler_test.go
- magefiles/magefile.go
The use of the golangci-lint linter has been disabled. See issue #302
https://github.com/vugu/vugu/issues/302
This prevents vugu from building with both Go 1.22.6 and 1.23.
At the time of writing the tinygo compiler tool chain has not been updated to support Go 1.23+.
This prevents vugu from building with Go 1.23
Applying both of these changes restores building vugu with both Go 1.22.6 and 1.23.
> Disable the linter and TestTinygoCompiler test case so vugu builds again

- gen/missing-fixer.go
- gen/parser-go-pkg.go
- magefiles/magefile.go
Using a golangci-lint directive of the form:
//nolint:staticcheck // reason why staticcheck has been disabled
We can disable the use of the staticcheck linter completely at the blocks or lines where is is currently reporting the use of the deprecated ast.Package stuct.
This approach is documented here:
https://golangci-lint.run/usage/false-positives/#nolint-directive
At present golangci-lint will ignore staticheck //lint:ignore style directives. This issues has been raised with the golangci-lint team. See:
https://github.com/golangci/golangci-lint/issues/2671#issuecomment-2310658099 and here:
https://github.com/golangci/golangci-lint/issues/1658#issuecomment-2312129214
> Re-enable linting via golangci-lint

- magefiles/consts.go
- magefiles/gitcmd.go
- magefiles/gocmd.go
- magefiles/modulehandler.go
The Go Wiki states:
Note: The same major Go version of the compiler and wasm_exec.js support file must be used together. That is, if main.wasm file is compiled using Go version 1.N, the corresponding wasm_exec.js file must also be copied from Go version 1.N. Other combinations are not supported.
See:
https://go.dev/wiki/WebAssembly
For the standard Go compiler ONLY this commit ensures that the above is true for modules under both the wasm-test-suite and examples directories.
It will also print a warning and a diff if a local repo copy of wasm_exec.js differs from the GOROOT version.
The warning states that the GOROOT version will be used i.e. the local copy will be overwritten. This is to ensure that the correct version of wasm_exec.js for the compiler version in use is used. The warning …
> Ensure that wasm_exec.js file is always copied from the GOROOT

- legacy-wasm-test-suite/test-020-vgform/go.mod
Bumping the verison of goimports brings in golang/x/text v0.17.0. This causes a version bump of golang/x/text used by legacy-wasm-test-suite/test-020-vgform from v0.14.0 to v0.17.0
> Bump the dependencies of legacy-wasm-test-suite/test-020-vgform

- .github/workflows/go-oldstable.yml
- .github/workflows/go-stable.yml
- magefiles/magefile.go
Update the magefile to add a new `InstallGoImports` target.
This target first checks if any version of gimports can be found on the path. If not then it installs the latest version of the latest version of the goimports command via:
go install golang.org/x/tools/cmd/goimports@latest
The @latest ensures that the dependencies listed in the root go.mod of vugu are left unchanged.
> Optionally install the goimports via the magefile and not via Github Action

- devutil/tinygo-compiler_test.go
(Re)Enable the tinygo compiler test now that tinygo supports go 1.23 as of tinygo v0.33.
See:
https://github.com/tinygo-org/tinygo/releases/tag/v0.33.0
> Enable the tinygo compiler test now tinygo supports go 1.23

- examples/Readme.md
Initial version of teh top level Readme.md in the examples directory. This readme contains the generalised build instructions for the examples, in particular if building without using mage.
> Initial version of the top level examples/Readme.md build instructions

- README.md
This reverts commit 63286ab07d5c25af547692dca3a10e1e0704e5cb.
Opps, commit 63286ab accidently removes the entire README.md file, and not a duplicate of it. This commit reverses the deletion  and restores the file.
Without a README.md file, Github has been unable to display any project information to visitors to the vugu repo. With this commit Github will be abe to display the project inforation once again.
> Revert "Oops- remove the duplicate and out dated Readme."

- examples/compound-component/.gitignore
- examples/html-form/.gitignore
- examples/vg-if/.gitignore
Fix: Corrects a typo in the .gitignore of soem of the examples.
> Oops: Fix a typo in the .gitignore in some of the examples

- staticrender/renderer-static_test.go
Added a static renderer test that makes a call into the `vugu/js` package. The test will be built for and run on the native target.
This test confirms that vugu/js is as functional as we need i.e. it does not panic on targets other than `GOOS=js GOARCH=wasm`.
This is test is related to Issues #330 and #328
https://github.com/vugu/vugu/issues/330
https://github.com/vugu/vugu/issues/328
> Add a static render test that calls into vugu/js

- magefiles/consts.go
- magefiles/go.mod
- magefiles/go.sum
- magefiles/gocmd.go
- magefiles/modulehandler.go
Go 1.24 changed the location of the wasm_exec.js file from:
$GOROOT/misc/wasm
to
$GOROOT/lib/wasm
See the relase notes for go1.24.
As we currently still build using go1.23 (the current oldstable release) the magefiles need to be updated to account for this change.
This change can be removed once go.1.25 arrives in Aug 2025. At that point both the stable and oldstable releases will used the newer $GOROOT/lib/wasm directory.
> Copy the wasm_exec.js file from the correct location pre and post go1.24

- staticrender/renderer-static_test.go
The staticrender ValueOf tests will only ever be executed on a GOOS=!js || GOARCH=!wasm platform i.e, on the native platform only.
Because the test uses the limited, but cross platform vugu/js nonjs implementation of the package we expect the test to panic.
The test has now been updated to expect the panic string.
If this test were to fail in the future it would indicate that the wrong vugu/js implementation has been called.
> Fix the staticrender ValueOf test
